apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-box-nodeport
  namespace: default
  labels:
    app: kube-box-nodeport
spec:
  selector:
    matchLabels:
      app: kube-box-nodeport
  template:
    metadata:
      labels:
        app: kube-box-nodeport
    spec:
      tolerations:
      # this toleration is to have the daemonset runnable on master nodes
      # remove it if your masters can't run pods
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: client
        image: sgfoot/kube-box:latest
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 9110
            protocol: TCP 
        env:
          - name: VERSION
            value: "v0.0.1"
          - name: PORT
            value: "9110"
          - name: TARGET_PORT
            value: "9110"
          - name: DATA_PATH
            value: "/work/data/"
          - name: IP_DATA_FILENAME
            value: "ip.data"
          - name: NETWORK_NAME
            value: "eth0"
          - name: GO_NUMBER
            value: "12"
          - name: TIMEOUT
            value: "3"
          - name: HEALTHZ_PATH_NAME
            value: "healthz"
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi

---
apiVersion: v1
kind: Service
metadata:
  name: kube-box-nodeport
  namespace: default
spec:
  selector:
    app: kube-box-nodeport
  type: NodePort
  ports:
  - name: kube-box-nodeport
    protocol: TCP
    port: 9110
    targetPort: http
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
    nodePort: 30008
