apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-box-prome
  namespace: default
  labels:
    app: kube-box-prome
spec:
  selector:
    matchLabels:
      app: kube-box-prome
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kube-box-prome
    spec:
      containers:
        - name: kube-box-prome
          image: sgfoot/kube-box:latest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          ports:
            - containerPort: 80
              name: http
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: kube-box-prome
  namespace: default
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "80"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
spec:
  selector:
    app: kube-box-prome
  type: ClusterIP
  ports:
    - name: kube-box-prome
      protocol: TCP
      port: 80
      targetPort: http
